export const userInputs = [
  {
    id: 1,
    label: "Username",
    type: "text",
    placeholder: "john_doe",
    name: "username",
  },
  {
    id: 2,
    label: "Password",
    type: "text",
    name: "password",
  },
  {
    id: 3,
    label: "First Name",
    type: "text",
    placeholder: "John",
    name: "first_name",
  },
  {
    id: 4,
    label: "Last Name",
    type: "text",
    placeholder: "Doe",
    name: "last_name",
  },
  {
    id: 5,
    label: "Email Address",
    type: "text",
    placeholder: "john_doe@gmail.com",
    name: "email_address",
  },
  {
    id: 6,
    label: "Phone NUmber",
    type: "text",
    placeholder: "+1 234 567 89",
    name: "phone_number",
  },
  {
    id: 7,
    label: "Address",
    type: "text",
    placeholder: "Elton St. 216 NewYork",
    name: "address",
  },
  {
    id: 8,
    label: "Department",
    type: "text",
    placeholder: "IT",
    name: "department",
  },
];

export const productInputs = [
  {
    id: 1,
    label: "Name",
    type: "text",
    placeholder: "Apple Macbook Pro",
    name: "name",
  },
  {
    id: 2,
    label: "Description",
    type: "text",
    placeholder: "Description",
    name: "description",
  },
  {
    id: 3,
    label: "Category",
    type: "text",
    placeholder: "1",
    name: "category",
  },
  {
    id: 4,
    label: "Tax Type",
    type: "text",
    placeholder: "D",
    name: "tax_type",
  },
  {
    id: 5,
    label: "Product Type",
    type: "text",
    placeholder: "1",
    name: "product_type",
  },
  {
    id: 6,
    label: "Unit",
    type: "text",
    placeholder: "u",
    name: "unit",
  },
  {
    id: 7,
    label: "Limited",
    type: "text",
    placeholder: "false",
    name: "limited",
  },
  {
    id: 8,
    label: "Active for Sale",
    type: "text",
    placeholder: "true",
    name: "active_for_sale",
  },
  {
    id: 9,
    label: "Packaging Unit",
    type: "text",
    placeholder: "CT",
    name: "packaging_unit",
  },
  {
    id: 10,
    label: "Code",
    type: "text",
    placeholder: "123",
    name: "code",
  },
];

export const supplierInputs = [
  {
    id: 1,
    label: "Name",
    type: "text",
    placeholder: "Suppliers",
    name: "name",
  },

  {
    id: 2,
    label: "Email Address",
    type: "text",
    placeholder: "suppliers@gmail.com",
    name: "email_address",
  },
  {
    id: 3,
    label: "Phone Number",
    type: "text",
    placeholder: "+1 234 567 89",
    name: "phone_number",
  },
  {
    id: 4,
    label: "Address",
    type: "text",
    placeholder: "Elton St. 216 NewYork",
    name: "address",
  },
];
